### PR TITLE
mysql: autocorrect semi-sync timeout

### PR DESCRIPTION
**Pull request by prettyshuang**

### CODE REVIEW

**Comment by BohuTANG** [comment]
@prettyshuang 

Codecov failed, please fix.

**Comment by prettyshuang** [comment]
push uddate：
add TestRaftLeaderCheckSemiSync

**Comment by prettyshuang** [comment]
push update:
fix TestCLIRaftCommand failed

**Comment by prettyshuang** [comment]
push update:
add .codecov.yml

**Comment by prettyshuang** [comment]
push update:
.codecov.yml: patch disable

**Comment by BohuTANG** [comment]
LGTM

**Pull request merged**
