### PR TITLE
*: add monitor-disabled config to allow disable mysql monitor

### PR DESCRIPTION
**Pull request by zhyass**
*: add monitor-disabled config to allow disable mysql monitor
update .gitignore

### CODE REVIEW

**Review by andyli029 — COMMENTED** [review]
Need add test to server_test.go?

**Comment by hustjieke** [comment]
Some test run failed: 
```
=== RUN   TestCLIMysqlCommand
 2021/03/31 11:05:57.016479 server.go:186:    	 [PANIC] 	server.rpc.start.error[listen tcp 10.1.0.4:8084: bind: address already in use
```

**Comment by zhyass** [comment]
> Some test run failed:
> 
> ```
> === RUN   TestCLIMysqlCommand
>  2021/03/31 11:05:57.016479 server.go:186:    	 [PANIC] 	server.rpc.start.error[listen tcp 10.1.0.4:8084: bind: address already in use
> ```

success

**Comment by hustjieke** [comment]
LGTM.

**Comment by andyli029** [comment]
LGTM

**Pull request merged**
