### PR TITLE
*: add http api for adapt kubernetes

### PR DESCRIPTION
**Pull request by zhyass**
[summary]
By using api can fix the kubernetes container memory increase unexpected bug.

https://github.com/zhyass/mysql-operator/issues/17

Before:
https://github.com/zhyass/mysql-operator/blob/master/cluster/syncer/status.go#L270

memory: 230+ M

After:

https://github.com/zhyass/radondb-mysql-kubernetes/blob/meg/cluster/syncer/status.go#L281

memory: 17M

### CODE REVIEW

**Comment by hustjieke** [comment]
radondb:feature_adapt_k8s should merge commits with main feature first.

**Comment by zhyass** [comment]
> radondb:feature_adapt_k8s should merge commits with main feature first.

The main feature has been merged.

**Comment by hustjieke** [comment]
LGTM.

**Review by andyli029 — COMMENTED** [review]
Ping @drdstech

**Comment by drdstech** [comment]
Advice:
1. Add security authentication
2. Add configuration items to set whether or not the RESTful API is enabled

**Comment by zhyass** [comment]
> Advice:
> 
>     1. Add security authentication
> 
>     2. Add configuration items to set whether or not the RESTful API is enabled

Done.

**Comment by drdstech** [comment]
LGTM

**Comment by andyli029** [comment]
LGTM.

**Pull request merged**
